{
    "name": "Product Management",
    "summary": "Manage internal product information for customer consultation",
    "version": "19.0.1.0.0",
    "category": "Inventory",
    "author": "Product Management PV",
    "license": "LGPL-3",
    "depends": [
        "base",
    ],
    "data": [
        "security/product_management_groups.xml",
        "security/ir.model.access.csv",
        "views/category_views.xml",
        "views/product_views.xml",
        "views/product_compare_views.xml",
        "views/account_views.xml",
        "views/dashboard_views.xml",
        "views/product_management_menus.xml",
        "data/test/test_categories.xml",
        "data/test/test_brands.xml",
        "data/test/test_category_fields.xml",
        "data/test/test_products.xml",
    ],
    "demo": [],
    "application": True,
    "installable": True,
}
