[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo

db_host = db
db_port = 5432
db_user = odoo
db_name = product_management_prod
dbfilter = ^product_management_prod$

log_level = info
http_interface = 0.0.0.0
proxy_mode = True
list_db = False
